import "dotenv/config";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { cuesToTimestampedText, fetchSubtitleTrack } from "./subtitles.js";
import { extractRiddles } from "./riddles.js";
import { formatConsole, formatMarkdown } from "./format.js";
import { parseVideoId, toWatchUrl } from "./youtube.js";
import type { ExtractionResult } from "./types.js";

async function main() {
  const input = process.argv[2];
  if (!input) {
    console.error(
      "使い方: npm run extract -- <YouTubeのURLまたは動画ID>\n" +
        "例    : npm run extract -- https://www.youtube.com/watch?v=XXXXXXXXXXX",
    );
    process.exit(1);
  }

  if (!process.env.ANTHROPIC_API_KEY) {
    console.error(
      "環境変数 ANTHROPIC_API_KEY が設定されていません。.env.example を参考に .env を作成してください。",
    );
    process.exit(1);
  }

  const videoId = parseVideoId(input);
  const videoUrl = toWatchUrl(videoId);

  console.log(`字幕を取得しています... (${videoUrl})`);
  const track = await fetchSubtitleTrack(videoId);
  console.log(`字幕を取得しました: ${track.cues.length}行 (言語: ${track.languageCode})`);

  const transcript = cuesToTimestampedText(track.cues);

  console.log("Claudeでなぞなぞを抽出しています...");
  const { riddles, transcriptTruncated } = await extractRiddles(transcript);

  if (transcriptTruncated) {
    console.warn(
      "警告: 文字起こしが長すぎたため、後半部分は抽出対象から切り詰められました。",
    );
  }

  const result: ExtractionResult = {
    videoId,
    videoUrl,
    videoTitle: track.title,
    sourceLanguage: track.languageCode,
    isAutoGenerated: track.isAutoGenerated,
    extractedAt: new Date().toISOString(),
    riddles,
  };

  const outDir = path.join(process.cwd(), "output");
  await mkdir(outDir, { recursive: true });

  const jsonPath = path.join(outDir, `${videoId}.json`);
  const mdPath = path.join(outDir, `${videoId}.md`);

  await writeFile(jsonPath, JSON.stringify(result, null, 2), "utf-8");
  await writeFile(mdPath, formatMarkdown(result), "utf-8");

  console.log("");
  console.log(formatConsole(result));
  console.log(`保存しました: ${jsonPath}`);
  console.log(`保存しました: ${mdPath}`);
}

main().catch((err) => {
  console.error(`エラー: ${err instanceof Error ? err.message : String(err)}`);
  process.exit(1);
});
