import { execFile } from "node:child_process";
import { mkdtemp, readdir, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { promisify } from "node:util";
import type { SubtitleCue, SubtitleTrack } from "./types.js";
import { toWatchUrl } from "./youtube.js";

const execFileAsync = promisify(execFile);

const PREFERRED_LANGS = ["ja", "ja-orig", "ja-JP"];

interface Json3Event {
  tStartMs?: number;
  segs?: { utf8?: string }[];
}

interface Json3Document {
  events?: Json3Event[];
}

function parseJson3(raw: string): SubtitleCue[] {
  const doc = JSON.parse(raw) as Json3Document;
  const cues: SubtitleCue[] = [];

  for (const event of doc.events ?? []) {
    if (!event.segs || typeof event.tStartMs !== "number") continue;
    const text = event.segs
      .map((seg) => seg.utf8 ?? "")
      .join("")
      .replace(/\n/g, " ")
      .trim();
    if (!text) continue;
    cues.push({ startMs: event.tStartMs, text });
  }

  return cues;
}

async function findYtDlpBinary(): Promise<string> {
  const candidates = [process.env.YT_DLP_PATH, "yt-dlp"].filter(
    (v): v is string => Boolean(v),
  );

  for (const candidate of candidates) {
    try {
      await execFileAsync(candidate, ["--version"]);
      return candidate;
    } catch {
      // try next candidate
    }
  }

  throw new Error(
    "yt-dlp が見つかりませんでした。`pip install -U yt-dlp` または " +
      "`brew install yt-dlp` 等でインストールしてから再実行してください " +
      "(YT_DLP_PATH 環境変数でパスを明示することもできます)。",
  );
}

/**
 * yt-dlp で字幕(手動優先、なければ自動生成)を json3 形式でダウンロードし、パースする。
 * 追加の yt-dlp 引数は EXTRA_YTDLP_ARGS 環境変数(スペース区切り)で渡せる。
 */
export async function fetchSubtitleTrack(
  videoId: string,
): Promise<SubtitleTrack> {
  const ytDlp = await findYtDlpBinary();
  const workDir = await mkdtemp(path.join(tmpdir(), "chatasset-subs-"));
  const outTemplate = path.join(workDir, "%(id)s");
  const extraArgs = (process.env.EXTRA_YTDLP_ARGS ?? "")
    .split(" ")
    .map((s) => s.trim())
    .filter(Boolean);

  const args = [
    "--skip-download",
    "--write-subs",
    "--write-auto-subs",
    "--sub-langs",
    PREFERRED_LANGS.join(","),
    "--sub-format",
    "json3",
    "--print",
    "%(title)s\t%(uploader)s",
    "-o",
    outTemplate,
    ...extraArgs,
    toWatchUrl(videoId),
  ];

  try {
    const { stdout } = await execFileAsync(ytDlp, args, {
      maxBuffer: 1024 * 1024 * 32,
    });
    const [title, uploader] = (stdout.split("\n")[0] ?? "").split("\t");

    const files = await readdir(workDir);
    const subFiles = files.filter((f) => f.endsWith(".json3"));

    if (subFiles.length === 0) {
      throw new Error(
        "この動画には日本語字幕(手動・自動生成とも)が見つかりませんでした。" +
          "別の動画を試すか、字幕付きの動画を指定してください。",
      );
    }

    const chosen =
      subFiles.find((f) => PREFERRED_LANGS.some((lang) => f.includes(`.${lang}.`))) ??
      subFiles[0];
    const languageMatch = chosen.match(/\.([a-zA-Z-]+)\.json3$/);
    const languageCode = languageMatch ? languageMatch[1] : "unknown";

    const raw = await readFile(path.join(workDir, chosen), "utf-8");
    const cues = parseJson3(raw);

    if (cues.length === 0) {
      throw new Error("字幕ファイルは取得できましたが、中身が空でした。");
    }

    return {
      videoId,
      languageCode,
      isAutoGenerated: true,
      cues,
      title: title || null,
      uploader: uploader || null,
    };
  } finally {
    await rm(workDir, { recursive: true, force: true });
  }
}

export function cuesToTimestampedText(cues: SubtitleCue[]): string {
  return cues
    .map((cue) => {
      const totalSeconds = Math.floor(cue.startMs / 1000);
      const minutes = Math.floor(totalSeconds / 60);
      const seconds = totalSeconds % 60;
      const timestamp = `${minutes}:${seconds.toString().padStart(2, "0")}`;
      return `[${timestamp}] ${cue.text}`;
    })
    .join("\n");
}
