export interface SubtitleCue {
  startMs: number;
  text: string;
}

export interface SubtitleTrack {
  videoId: string;
  languageCode: string;
  isAutoGenerated: boolean;
  cues: SubtitleCue[];
  title: string | null;
  uploader: string | null;
}

/**
 * このなぞなぞが「昔から知られている定番なぞなぞ」か「特定の作者・チャンネルの創作の
 * 可能性が高いもの」かのAIによる暫定判定。著作権配慮のための目安であり、実際に
 * アプリへ収録する前に人間が確認すること。
 */
export type OriginGuess = "traditional" | "possibly_original" | "unknown";

export interface Riddle {
  index: number;
  japaneseQuestion: string;
  japaneseAnswer: string;
  /** 直訳ではなく、英語話者が同じように勘違い→意外性を体験できるよう再構成した問題文 */
  englishQuestion: string;
  englishAnswer: string;
  /** ゲームのテンポを壊さない、1〜2文程度の簡潔な解説。なぞなぞとして成立する場合は空文字も可 */
  explanation: string;
  /** 言葉遊びの構造上、英語では成立しにくく採用を推奨しない場合に true */
  notRecommendedForEnglish: boolean;
  /** notRecommendedForEnglish が true の場合の理由 */
  notRecommendedReason: string;
  originGuess: OriginGuess;
  approxTimestampSeconds: number | null;
}

export interface ExtractionResult {
  videoId: string;
  videoUrl: string;
  videoTitle: string | null;
  sourceLanguage: string;
  isAutoGenerated: boolean;
  extractedAt: string;
  riddles: Riddle[];
}
